### ISSUE TITLE
スライドか動画制作かについて

### ISSUE THREAD

**Issue by novuky** [quad9/syun_jyu_kai_presentation#10]
### 高広から

昨日も打ち合わせでお伝えしましたが、現状では、

* プレゼンテーションのスライドをkeynoteで制作する
* プレゼンテーション用の動画をkeynote+動画制作ソフト（例えばiMovieなど）で制作する

の方向が決まっていません。

今夕の顧客との打ち合わせで決定する予定です。

深沢さんには、先日提示しました予算内で、動画を作成するとなった場合でも仕事をしていただけるか、はっきりとした意思確認をしておりませんでした。

ご検討ください。その回答を待って本日の打ち合わせに望みます。よろしくお願いします。

**Comment by witchdoktor** [comment]
動画をつくる場合はiMovie組み込み機能のエンドロールなら作れそうです。
簡単にサンプルをつくったのでご確認ください。
https://www.dropbox.com/s/ezn5it7fghpsbg2/%E3%82%B9%E3%82%BF%E3%83%83%E3%83%95%E3%83%AD%E3%83%BC%E3%83%AB%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB.mp4?dl=0

- 背景画像は任意のものに変更可能
- 文字の流れるスピードは調整可能
- フォントとサイズは変更可能
- ドロップシャドウなどのエフェクトは変更できなさそう

私だとこれくらいしかできなさそうです。あくまでスライドが主役ということで、あまり映像のクオリティを追うということは難しそうなので、そこの期待値はあまり上げないようにお願いしたいです。

**Comment by witchdoktor** [comment]
なるほど。
iMovieで動画完パケにしてしまうと、話の流れにタイミングを合わせてスライドを切り替えることができなくなってしまいます。手慣れたスピーカーでもムービーの尺に合わせてしゃべることは難しく、オススメしません。音楽をつけることに関しては、先日述べたとおりでこちらもオススメしないです。
ということで、スライドの映像化に関してはあまり選択肢に入れないほうがいいように思います。

**Comment by novuky** [comment]
顧客との打ち合わせを終えました。
報告します。

* スライドのプレゼンテーションの体を成しているが動画を流し、それに合わせるよう演者がスピーチをする。
* 動画に音楽を入れる。
* 4:3か16:9か、また、スクリーンの解像度などの仕様については、帝国ホテルに問い合わせのうえ連絡する。
* 10分60枚のスライドを目処とする。また、10分以下を目指すよう努力する。
* 台割りは予定通り、9月6日に渡す。ただし、ラフ作成中の一週間で調整が入る可能性はある。
* ラフは、台割りの中で要素が多く入り全体を見渡しやすいものを選んで作成する。厳密に何枚ラフを作成ということはない。

ということでした。

また、構成について目処を立てていただきました。

* プロローグ
* 実績
  * 人権を守るポリシーの元、実際に政策にまで落とし込める実行力をもった団体であることのアピールする。
* 多彩な人材
  * 日本弁護士会会長、副会長、大阪弁護士会会長、副会長、多くの委員を送り出し、人権にまつわる多様な裁判に弁護団の中核として参加するなどを紹介する。
* 楽しさ
  * 会員交流にも力を入れ始めたこの10年。
* 女性会長（エンディング　最大の盛り上げ演出）
  * 以上の会員の努力により、大阪弁護士会　初の女性会長を送り出すに至る。

以上の構成を骨格として、大幅に現在の台割りの見直しを急ピッチでしていただく約束をしました。

先方曰く「今まで樹海の中にいたけど、やっと登山口にたどり着けた。この土日が勝負だから、よろしくお願いしますね。」と言葉をいただけたので、台割りを期日通りに気合い入れて仕上げてくると思います。

基本、9月7日からラフ作成ということで準備をお願いします。

最後に、深沢さんのおすすめ出来ないことが、2つとも実行されることになりましたが、先方が腹を括って決めたことなので、難易度が高かろうが真摯に練習して本番に臨むはずです。

そんな彼らをしっかりとサポートするものを作り上げたいと私は考えます。
以上、ご確認ください。

**Comment by novuky** [comment]
修正については出来るだけ無い方向で考えています。
予定カレンダー予定を変更していませんが、10月12日（金）納品となり、それまでの10月中一回の調整期日を設ける予定でおります。
納品後の修正はしない方向で話を持って行ってます。

ご指摘の点、制作にあたり改めて深沢さんに相談することになります。9月6日（木）、または、明けて7日（金）の打ち合わせ日時の調整をお願いします。ここに返信してください。待っております。

**Comment by novuky** [comment]
今朝、修正した台割りが上がってきました。
100枚から60枚と大幅にスライドを減らしてきました。私もそうですが、彼らなりに思惑があり、絶対に無様な失敗は出来ないという思いがあるからこその勢いを感じています。
現在、修正点はまだまだありますが、調整を大急ぎでやっていただいている次第です。

**Comment by witchdoktor** [comment]
承知しました、ありがとうございます。

打ち合わせの件、6日（木）の13時〜17時の間のどこかでいかがでしょう？

＝＝＝

あと一点、気になるところですが、スライド枚数については60枚ほどになりそうでしょうか。
当初の見積もり時に予定していた20枚〜40枚を大きく超えることになりまして、できればスライド一枚の単価にして5000円 / 枚よりは下げたくないのですが、40枚以内に調整することは難しそうでしょうか？

**Comment by witchdoktor** [comment]
わかりました。7日10時でお願いいたします。

枚数の件については申しわけありません、単純にスピーカー目線でお話していて費用の面がちゃんと考慮されていないお話でしたね…
では60枚まででなんとかします。

ただ、もし10分間で60枚になるとすると本当にカツカツの進行になるので、そこはお気をつけください。その場合あらかじめ15分ほどの時間を予定したほうがよいかもしれません。

**Comment by quad9** [comment]
ご理解していただきありがとうございます。
10分以内で抑えるよう急いで台割りのリライトしなければいけない現状で、お客さんと意識の共有はできています。
だからこそ、先週末の打ち合わせ後、お客さんが100枚のスライドを60枚までリライトして月曜日に提出してこられました。素人仕事かもしれませんが、彼らの努力は評価してあげてもいいと思います。
原稿作成段階ですので予断を許しませんが、10分以内、60枚以内、目標はなんとか50枚まででまとめるように打ち合わせて行くつもりです。
一旦このIssueはここで打ち切ります。

**Comment by witchdoktor** [comment]
承知いたしました！ はい、できる限りお客さまの熱意にそえるよう頑張りたいと思います。どうぞ宜しくお願いいたします。
