### ISSUE TITLE
テストとして、材料送信ブランチかIssueを送る

### ISSUE THREAD

**Issue by novuky** [quad9/syun_jyu_kai_presentation#6]
## Issuesのテスト送信

テストとしてだけの送信ではもったいないので、深沢さんに連絡をします。
現状、テストファイルや材料がありますが、これからは完全に深沢さんのいつもやっておられる環境を構築してください。
つまり、今あるものは全て破棄していただいて結構です。

* List
* List
* List

```
def greeting
  puts "Hello, New World!"
end
```

なるほど、マークダウンに対応ということらしいです。

以上、よろしくお願いします。

**Comment by quad9** [comment]
master以外のリポジトリではIssuesに投稿があったかどうかはわからない。

つまり、マスターと各リポジトリ（ブランチという言い方のほうがいいのか？）とのやり取りをするためのツールというわけですね。
理解しました。
